port:
  number:
    min: 8480
    max: 8489

spring:
  application:
    name: calc-builder-roof
  jackson:
    serialization:
      INDENT_OUTPUT: true

eureka:
  instance:
    appname: calc-builder-roof
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: Calculation Roof service
    description: This is a service to calculate the price of the roof
    version: 1.0.0

basement:
  price:
    roofWorks: 1500
