port:
  number:
    min: 8380
    max: 8389

spring:
  application:
    name: calc-builder-walls
  jackson:
    serialization:
      INDENT_OUTPUT: true

eureka:
  instance:
    appname: calc-builder-walls
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: Calculation walls service
    description: This is a service to calculate the price of the walls
    version: 1.0.0

basement:
  price:
    wallsWorks: 5000
