port:
  number:
    min: 8280
    max: 8289

spring:
  application:
    name: calc-builder-basement
  jackson:
    serialization:
      INDENT_OUTPUT: true

eureka:
  instance:
    appname: calc-builder-basement
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: Calculation basement service
    description: This is a service to calculate the price of the basement
    version: 1.0.0

basement:
  price:
    concrete: 1500
    landWorks: 1000


---

spring:
  profiles: heroku
  
eureka:
  client:
    serviceUrl:
      defaultZone: https://calcbuilder-eureka.herokuapp.com
