port:
  number:
    min: 8180
    max: 8189

spring:
  application:
    name: calc-builder-house
  jackson:
    serialization:
      INDENT_OUTPUT: true

eureka:
  instance:
    appname: calc-builder-house
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint: 
    health: 
      show-details: always

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
      isolation:
        thread:
          timeoutInMilliseconds: 5000
          
info:
  app:
    name: Calculation hause service
    description: This is a service to calculate how much does it cost to build a house
    version: 1.0.0

logging:
  level:
   com.netflix.hystrix: DEBUG
   
